/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apkscanner_core_scanner_AaptNativeScanner */

#ifndef _Included_com_apkscanner_core_scanner_AaptNativeScanner
#define _Included_com_apkscanner_core_scanner_AaptNativeScanner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apkscanner_core_scanner_AaptNativeScanner
 * Method:    createAssetManager
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_apkscanner_core_scanner_AaptNativeScanner_createAssetManager
  (JNIEnv *, jclass);

/*
 * Class:     com_apkscanner_core_scanner_AaptNativeScanner
 * Method:    realeaseAssetManager
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_apkscanner_core_scanner_AaptNativeScanner_realeaseAssetManager
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_apkscanner_core_scanner_AaptNativeScanner
 * Method:    getPackageId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_apkscanner_core_scanner_AaptNativeScanner_getPackageId
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_apkscanner_core_scanner_AaptNativeScanner
 * Method:    addPackage
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_apkscanner_core_scanner_AaptNativeScanner_addPackage
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_apkscanner_core_scanner_AaptNativeScanner
 * Method:    addResPackage
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_apkscanner_core_scanner_AaptNativeScanner_addResPackage
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_apkscanner_core_scanner_AaptNativeScanner
 * Method:    getResourceName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_apkscanner_core_scanner_AaptNativeScanner_getResourceName
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_apkscanner_core_scanner_AaptNativeScanner
 * Method:    getResourceType
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_apkscanner_core_scanner_AaptNativeScanner_getResourceType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_apkscanner_core_scanner_AaptNativeScanner
 * Method:    getResourceValues
 * Signature: (JI)[Lcom/apkscanner/data/apkinfo/ResourceInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_apkscanner_core_scanner_AaptNativeScanner_getResourceValues
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_apkscanner_core_scanner_AaptNativeScanner
 * Method:    getResourceString
 * Signature: (JILjava/lang/String;)Lcom/apkscanner/data/apkinfo/ResourceInfo;
 */
JNIEXPORT jobject JNICALL Java_com_apkscanner_core_scanner_AaptNativeScanner_getResourceString
  (JNIEnv *, jclass, jlong, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
